/* eslint-disable */
// @ts-nocheck
// biome-ignore lint: disable
// oxlint-disable
// ------
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399

export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    AppSidebar: typeof import('./src/components/app/AppSidebar.vue')['default']
    AppTopPannel: typeof import('./src/components/app/AppTopPannel.vue')['default']
    Avatar: typeof import('primevue/avatar')['default']
    Button: typeof import('primevue/button')['default']
    Image: typeof import('primevue/image')['default']
    Menu: typeof import('primevue/menu')['default']
    Menubar: typeof import('primevue/menubar')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    UserProfile: typeof import('./src/components/app/UserProfile.vue')['default']
  }
}
